version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorld"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9udxi87v9l04"
s3_prefix = "HelloWorld"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
